# Generated by Django 3.2.13 on 2022-04-24 12:21

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(upload_to='img_user', verbose_name='Firma Logo/ Görsel')),
                ('coverLetter', ckeditor.fields.RichTextField()),
                ('autoBiography', ckeditor.fields.RichTextField()),
                ('autoBiographyFile', models.FilePathField()),
                ('birtDate', models.DateTimeField(default=datetime.date.today)),
                ('skils', models.ManyToManyField(to='skils.Skils')),
            ],
        ),
    ]
