# Generated by Django 3.2.13 on 2022-04-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skils', '0001_initial'),
        ('accounts', '0003_auto_20220425_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofil',
            name='skils',
        ),
        migrations.AddField(
            model_name='userprofil',
            name='skils',
            field=models.ManyToManyField(to='skils.Skils'),
        ),
    ]
