# Generated by Django 3.2.13 on 2022-04-25 04:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_rename_picture_workers_picture'),
        ('accounts', '0005_auto_20220425_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='works',
            field=models.ManyToManyField(to='workers.Workers'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='autoBiography',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='coverLetter',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
