# Generated by Django 3.2.13 on 2022-04-25 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220425_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='birtDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
