# Generated by Django 3.2.13 on 2022-04-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofil_birtdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='birtDate',
            field=models.CharField(max_length=50),
        ),
    ]
