# Generated by Django 3.2.13 on 2022-04-24 03:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comName', models.CharField(max_length=50, verbose_name='Firma Adı')),
                ('comEmail', models.EmailField(max_length=254, verbose_name='Email Adresi')),
                ('comAddres', models.TextField(verbose_name='Firma Adresi')),
                ('comWebAdrdes', models.URLField(null=True, verbose_name='Firma Web Adresi')),
                ('comPicture', models.ImageField(upload_to='img_com', verbose_name='Firma Logo/ Görsel')),
                ('comPhoneNumber', models.BigIntegerField(verbose_name='Telefon Numarası')),
                ('comAbout', ckeditor.fields.RichTextField(verbose_name='Firma Hakkında')),
            ],
        ),
    ]
