# Generated by Django 3.2.13 on 2022-04-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='Picture',
            field=models.ImageField(default=2, upload_to='img_ad', verbose_name='Logo/ Görsel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workers',
            name='startDate',
            field=models.DateTimeField(verbose_name='İlan Tarihi'),
        ),
    ]
