# Generated by Django 3.2.13 on 2022-04-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20220424_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='Picture',
            new_name='picture',
        ),
    ]
